# Setup
title:        ChangeVision v1.0
tagline:      Плагин для создания версии сайта для слабовидящих
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Алексей Титевалов
  url:        http://changevision-plugin.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
